### ISSUE TITLE
default reject html file

### ISSUE THREAD

**Issue by nmr50** [porech/caddy-maxmind-geolocation#1]
Dear author, I'm very thankful for the plugin you made, but reminding ipfilter plugin for caddyv1 I want to ask you to make some (small?:) changes to your plugin - to add default html file that is used to show to rejected countries, like
"reject_file": ["getlost.html"]
I use zero time refresh to google, for example.

Thanks in advance !
-t

**Comment by ale-rinaldi** [comment]
Hello @nmr50 ,

thanks for reaching out, and I'm really happy to hear that this plugin suits your needings :)

About your request, this is not how Caddy2 matchers are intended to work. For them to be clean, they should just match something, and not take decisions/do something based on the match result.

The right way to do this in Caddy2 is to define different handlers based on the matchers. Below is an example that should work for your case.

It's probably not the cleanest way to write it, the `@wrongcountry` declaration could probably be just a negation of `@mygeofilter` instead of reverse re-declaring the entire matcher... But I didn't quickly find the right syntax so I let this up to you :) however, it just works, assuming you have your website in `/var/www/html` and the page you want to display as fallback in `/var/www/fallback/wrong-country.html`:

```
test.example.org {
  @mygeofilter {
    maxmind_geolocation {
      db_path "/usr/share/GeoIP/GeoLite2-Country.mmdb"
      allow_countries IT FR
    }
  }

  @wrongcountry {
    maxmind_geolocation {
      db_path "/usr/share/GeoIP/GeoLite2-Country.mmdb"
      deny_countries IT FR
    }
  }

   file_server @mygeofilter {
     root /var/www/html
   }


   file_server @wrongcountry {
     root /var/www/fallback
   }
   rewrite @wrongcountry /wrong-country.html
}
```

Please let me know if this solves the issue 👍 

Thanks again!

**Comment by nmr50** [comment]
Hello Ale - someone's already told me to do that:
```
        root * /home/tmh/caddy/web

        @blocked1 not maxmind_geolocation {
                db_path "/home/tmh/caddy/geolite/GeoLite2-Country.mmdb"
                allow_countries RU IL FR
        }
        rewrite @blocked1 def.html

```
-- but problem that I see when I connect to my web server from NOT LISTED countries above - I see 404 error, page not found - instead of content/execution def.html:
`<meta http-equiv="refresh" content="0; url=http://google.com" />`

So - that is why I ask you to add reject html file as variable, if its possible, of course :)
Thanks in advance !

**Comment by ale-rinaldi** [comment]
Hello @nmr50 ,

can you post the entire config file (obfuscating the actual domain name, if you want) so that I can give it a try?

With the configuration I posted you as example, everything works as you expect:
- the actual website in /var/www/html is displayed for Italy and French
- the content of /var/www/fallback/wrong-country.html is displayed to all the other ones, whichever path they call

Isn't this what you're looking for?

**Comment by nmr50** [comment]
OK, here I go:
```
https://v4.site, https://v6.site {
        log {
                output file access.log
        }

        root * /home/tmh/caddy/web

        @blocked1 not maxmind_geolocation {
                db_path "/home/tmh/caddy/geolite/GeoLite2-Country.mmdb"
                allow_countries RU IL FR
        }
        rewrite @blocked1 def.html

        @blocked2 {
                path /private/one*
                not maxmind_geolocation {
                db_path "/home/tmh/caddy/geolite/GeoLite2-Country.mmdb"
                allow_countries RU IL
                }
        }
        rewrite @blocked2 def.html

        file_server
}
```
Yes, I am looking the same rule as you said - allow_countries RU IL FR - show content to them - OTHER countries are redirected to def.html (with redirect to google.com), yet second rule is more secured - allow_countries RU IL, and - again - OTHER countries are redirected to def.html.

I just thought that variable with denial web page file will be more useful - like - reject_html_file "def.html" - in the same section where allow_countries or deny_countries are located.

What d'ya think ?:)

**Comment by ale-rinaldi** [comment]
The problem with the approach of the denial web page is that it would break other things, for example a more complex chain of matchers. Just imagine that a matcher is evaluated with some other ones to determine if the user can access or not a specific resource; the fact that just this single one doesn't match would immediately block the chain and return the page, that is not how matchers are intended to work.

If I got it right, what you want is that users from RU, IL and FR can access the website, but only users from RU and IL can access the private paths. Is it right?

**Comment by nmr50** [comment]
Sorry, man, I'm not into coding and I don't understand those matches, chain things in v2 config :[

> If I got it right, what you want is that users from RU, IL and FR can access the website, but only users from RU and IL can access the private paths. Is it right?
Yes, while RU, IL and FR have access to whole website, only RU and IL countries are permitted to access private part of the site, others are (supposed to be) redirected to def.html.

btw, I asked many ppl - all of them pointed me to examine caddy v2 manual, but I DO NOT GET how to change this log output:
2021/01/27 15:49:23.699 error   http.log.access.log0    handled request {"request": {"remote_addr": "114.119.145.139:43808", "proto": "HTTP/1.1", "method": "GET", "host": "mysite", "uri": "/robots.txt", "headers": {"Accept": [
TO
2021.01.27 15:49.23 ip.ip.ip.ip path result code
CAN YOU - PLEASE - tell me how to change first raw log output to second nice one - on the second line ?

BIG THANKS in advance! :)

**Comment by nmr50** [comment]
Hello again ! Tell me please - any updates on 1st question, or 2nd with logfile format ?:) Thanks in advance !

**Comment by nmr50** [comment]
OK, Sorry for some mess with logfile format - can we return to the main topic - why Caddy (plugin of yours?:) just gives out '404' (no page available) instead of redirecting unwanted country users to def.html where refresh to google.com is located ?
Thank in advance !!!

**Comment by nmr50** [comment]
Hello Ale-Rinaldi! I did solve (_unrelated_) topic about logfile format, sorries - and
I **still** need help about rejecting unwanted countries' users with defined html file - and this is NOT happening !
Tell me, please, do you have an IRC account/session on networks like IRC.LIBERA.CHAT or IRC.FREENODE.NET IRC networks ?
If YES - it will be much better to have conversaion in real time, when you'll have a free time of course !

I'll be waiting for your reply,
Thanks in advnce !
-t
